# Day 04 : Hexagons

```{r}
# data source, % benefits: https://dashboards.instantatlas.com/viewer/report?appid=b0aa98ed7113440581b4b3513ebb6e3d

man_bens_raw <- readxl::read_xlsx(here::here("raw_data/Area_Profile_Data_-_November_2021.xlsx"), sheet = "Benefits DWP (February 2021)")

man_bens <-
  man_bens_raw %>%
  filter(Area == "Ward") %>%
  select(ward = "Area Name" , pc_out_work_bens = "Percentage of residents claiming out of work benefits") %>%
  mutate(pc_out_work_bens = pc_out_work_bens/100)

```

```{r}
# boundaries
# boundary source: https://osdatahub.os.uk/downloads/open/BoundaryLine

library(sf)
library(geogrid)
library(rgdal)

uk_bound <- 
  readOGR( 
  dsn = here::here("raw_data/bdline_essh_gb/Data/GB"), 
  layer = "district_borough_unitary_ward_region",
  verbose=FALSE)

# convert to sf
uk_bound_sf <- st_as_sf(uk_bound)

man_bound_cln <-
  uk_bound_sf %>%
  filter(FILE_NAME == "MANCHESTER_DISTRICT_(B)")

```

```{r}
# calculate hexabin polygons

par(mfrow = c(2, 3), mar = c(0, 0, 2, 0))

# choose from output which is the most representative
for (i in 1:6) {
  new_cells <- calculate_grid(shape = man_bound_cln, grid_type = "hexagonal", seed = i)
  plot(new_cells, main = paste("Seed", i, sep = " "))
}

man_sf_hex <- calculate_grid(shape = man_bound_cln, grid_type = "hexagonal", seed = 6) # seed = chosen 
man_hex    <- assign_polygons(man_bound_cln, man_sf_hex)
  
```

```{r}

man_hex_bens <-
  man_hex %>%
  janitor::clean_names() %>%
  mutate(name = str_remove(name, "Ward"),
         name = trimws(name)) %>%
  rename(ward = "name") %>%
  select(ward , geometry, centroix, centroiy) %>%
  full_join(man_bens , by = "ward")

```

```{r}
# plot
font_add_google("Graduate", "graduate")

text1 <- str_wrap("The Manchester worker bee is one of the best-known symbols of Manchester and has been an emblem for the city for over 150 years. The bee denotes Mancunians' hard work ethic and the city being a hive of activity. It has also come to represent the sense of unity", 40)

text2 <- str_wrap("This hexamap shows the percentage of Mancunians still recieving out of work benefits in 2021 according to the Department of Work and Pensions (DWP). Unemployment in the North of England has consistently being above The South and the Pandemic has only furthered these inequalities.", 40)

plot_manchester <-
ggdraw(
man_hex_bens %>%
  ggplot() +
  geom_sf(aes(geometry = geometry, fill = pc_out_work_bens), color = "white") +
  #ggrepel::geom_label_repel(aes(label = ward, x = centroix, y = centroiy), size = 3) +
  rcartocolor::scale_fill_carto_c(palette = "PinkYl", labels = scales::percent_format(accuracy = 2)) +
  labs(fill = "% of Ward Population Receiving\nOut of Work Benefits") +
  theme_void() +
  theme(legend.position = c(0.75,0.015),
        legend.direction = "horizontal",
        legend.title.align = c(1),
        legend.title = element_text(family = "graduate"),
        legend.key.width = unit(1.5, "cm"),
        plot.margin = margin(0,-1,1,-4, unit = "cm"))) +
draw_image("https://i.etsystatic.com/14593570/r/il/be970c/1293079357/il_570xN.1293079357_kvsv.jpg",
           height = 0.15, width = 0.15, x = 0.35, y = 0.22) +
draw_text("Manchester\nand the\nWorker Bee" , x = 0.565, y = 0.45, hjust = 0, family = "graduate", size = 28) +
draw_text(text1, size = 8, x = 0.565, y = 0.30, hjust = 0, family = "graduate") +
draw_text(text2, size = 8, x = 0.565, y = 0.155, hjust = 0, family = "graduate")
         
```

#### Saving
```{r}

ggsave(plot = plot_manchester, filename = here::here("2021/Day 04 : Hexagons/D4_Manchester_Bee.jpeg"), dpi = 360, height = 10.2, width = 7, bg = "white")

```
